version: '3.9'

networks:
  streamnet:
    driver: bridge

services:
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    ports:
      - '1935:1935' # RTMP ingest
      - '8554:8554' # RTSP output
      - '8000:8000/udp' # RTP (optional)
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    networks:
      - streamnet
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-backend
    ports:
      - '6001:6001'
    volumes:
      - ./logs:/app/logs
    depends_on:
      - rtsp-server
    env_file: .env
    environment:
      - RTSP_BASE_URL=rtsp://rtsp-server:8554
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_IDS=${ADMIN_CHAT_IDS}
    networks:
      - streamnet
    restart: always

  ffmpeg-simulator:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg-simulator
    command:
      - ffmpeg
      - -re
      - -f
      - lavfi
      - -i
      - testsrc=size=640x360:rate=30
      - -f
      - lavfi
      - -i
      - sine=frequency=1000
      - -c:v
      - libx264
      - -c:a
      - aac
      - -f
      - flv
      - rtmp://rtsp-server:1935/live/test
    depends_on:
      - rtsp-server
    restart: always
    networks:
      - streamnet
