version: '3.9'

networks:
  streamnet:
    driver: bridge

services:
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    ports:
      - '1935:1935' # RTMP ingest
      - '8554:8554' # RTSP serve
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    command: ['/mediamtx.yml']
    networks:
      - streamnet
    restart: always

  ffmpeg-simulator:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: ffmpeg-simulator
    depends_on:
      - rtsp-server
    volumes:
      - ./videos:/videos
    command: >
      -re
      -f lavfi -i testsrc=size=640x360:rate=30
      -f lavfi -i sine=frequency=1000
      -c:v libx264 -preset veryfast -tune zerolatency
      -c:a aac
      -f flv rtmp://rtsp-server:1935/live/stream
    networks:
      - streamnet
    restart: 'no'

  backend:
    build:
      context: .
      dockerfile: Dockerfile # ваш Node.js на Alpine
    container_name: stream-backend
    ports:
      - '6001:6001'
    depends_on:
      - rtsp-server
    networks:
      - streamnet
    restart: always
