version: '3.9'

services:
  rtsp-server:
    image: aler9/rtsp-simple-server:latest
    container_name: rtsp-server
    ports:
      - '8554:8554' # RTSP
      - '8000:8000/udp' # RTP (optional)
    volumes:
      # Если нужно подменить конфиг, иначе сервер запустится с дефолтным
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml:ro
    restart: always
    networks:
      - streamnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-backend
    ports:
      - '6001:6001' # ваш NestJS API
    volumes:
      - ./logs:/app/logs # сюда ffmpeg будет писать логи потоков
    depends_on:
      - rtsp-server
    environment:
      # адрес вашего RTSP-сервера внутри Docker-сети
      RTSP_BASE_URL: rtsp://rtsp-server:8554
        - BOT_TOKEN=${BOT_TOKEN}
        - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    restart: always
    networks:
      - streamnet

networks:
  streamnet:
    driver: bridge
