version: '3.9'

services:
  rtsp-server:
    image: aler9/rtsp-simple-server:latest
    container_name: rtsp-server
    ports:
      - '1935:1935' # RTMP ingest
      - '8554:8554' # RTSP
      - '8000:8000/udp' # RTP (optional)
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    restart: always
    networks:
      - streamnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-backend
    ports:
      - '6001:6001'
    volumes:
      - ./logs:/app/logs
    depends_on:
      - rtsp-server
    environment:
      - RTSP_BASE_URL=rtsp://rtsp-server:8554
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_IDS=${ADMIN_CHAT_IDS}
    restart: always
    networks:
      - streamnet

networks:
  streamnet:
    driver: bridge
